### ISSUE TITLE
Update @aws-amplify/pushnotifiaction react native to support androidx library in android

### ISSUE THREAD

**Issue by AhmedMesawer** [aws-amplify/docs#2029]
**Describe the bug**
When try to build release in android it gives me that build failed because of syntax error. that happens because @aws-amplify/pushnotifiaction android depends on deprecated v7 support library and react-native 60 and above uses androidx

**To Reproduce**
1. migrate @aws-amplify/pushnotifiaction to use androidx

 - OS: android 9
- react-natvie 60 and above

**error stack**
```
> Task :aws-amplify_pushnotification:compileReleaseJavaWithJavac FAILED
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:16: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:34: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:28: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:29: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:132: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNPushNotificationAttributes
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                              ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:192: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                                 ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:191: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
                                   ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                                                                            ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:258: error: package NotificationCompat does not exist
            notification.setStyle(new NotificationCompat.BigTextStyle().bigText(bigText));
                                                        ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:309: error: cannot find symbol
                notification.setCategory(NotificationCompat.CATEGORY_CALL);
                                         ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
Note: E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aws-amplify_pushnotification:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9m 15s
```

**Comment by vincent-cy** [comment]
> **Describe the bug**
> When try to build release in android it gives me that build failed because of syntax error. that happens because @aws-amplify/pushnotifiaction android depends on deprecated v7 support library and react-native 60 and above uses androidx
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. migrate @aws-amplify/pushnotifiaction to use androidx
> 
> * OS: android 9
> * react-natvie 60 and above
> 
> **error stack**
> 
> ```
> > Task :aws-amplify_pushnotification:compileReleaseJavaWithJavac FAILED
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:16: error: package android.support.annotation does not exist
> import android.support.annotation.NonNull;
>                                  ^
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:34: error: cannot find symbol
> import android.support.v4.app.NotificationCompat;
>                              ^
>   symbol:   class NotificationCompat
>   location: package android.support.v4.app
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:28: error: cannot find symbol
> import android.support.v4.app.NotificationCompat;
>                              ^
>   symbol:   class NotificationCompat
>   location: package android.support.v4.app
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:29: error: package android.support.v4.content does not exist
> import android.support.v4.content.LocalBroadcastManager;
>                                  ^
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:132: error: cannot find symbol
>     @NonNull
>      ^
>   symbol:   class NonNull
>   location: class RNPushNotificationAttributes
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
>             NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
>                               ^
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:192: error: cannot find symbol
>                     .setPriority(NotificationCompat.PRIORITY_HIGH)
>                                  ^
>   symbol:   variable NotificationCompat
>   location: class RNPushNotificationHelper
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:191: error: cannot find symbol
>                     .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
>                                    ^
>   symbol:   variable NotificationCompat
>   location: class RNPushNotificationHelper
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
>             NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
>                                                                             ^
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:258: error: package NotificationCompat does not exist
>             notification.setStyle(new NotificationCompat.BigTextStyle().bigText(bigText));
>                                                         ^
> E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:309: error: cannot find symbol
>                 notification.setCategory(NotificationCompat.CATEGORY_CALL);
>                                          ^
>   symbol:   variable NotificationCompat
>   location: class RNPushNotificationHelper
> Note: E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 11 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':aws-amplify_pushnotification:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 9m 15s
> ```

hello .  
How did you solve the problem

**Comment by AhmedMesawer** [comment]
@vincent-cy I did not solve it, I opened it as an issue to be solved

**Comment by jamesonwilliams** [comment]
Hey @AhmedMesawer I updated the AWS SDK for Android to use Android X as of 2.17.x. Try the latest version, version 2.17.1.

**Comment by kuroiokami** [comment]
Any update on this issue?

**Comment by minayousseif** [comment]
Any update? Having the same error in a react-native 0.63.2 project.

**Comment by the-smart-home-maker** [comment]
I have the same issue - can not release any more as of this issue. Is there any fix to be available soon?

**Comment by minayousseif** [comment]
> Any update? Having the same issue when creating an android release build in a react-native 0.63.2 project.

We were able to fix the issue by using `jetifier`, we ran `npx jetifier` before the android build. Hope this helps anyone having the same issue.

**Comment by lucafronterotta** [comment]
I'm experiencing the same issue on a 0.63.2 RN project.
Even launching npx jetifier before build doesn't solve the problem

**Comment by lucafronterotta** [comment]
I solved the problem following step 3 of this guide:
https://enappd.com/blog/androidx-react-native/83/

Hope it will help others
